CREATE SEQUENCE IF NOT EXISTS booking_number_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999 NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS ticket_number_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999 NO CYCLE;
